name: "AutoencoderExperiment"
config:
  params:
    dataset: "LightCurveData"
    figures: []
    optimizer:
      name: Adam
      config:
        LR: 0.00001
        weight_decay: 0.0
    batch_size: 32